import json
import logging
import datetime
from jinja2 import Template, Environment


CEDAR_TEMPLATE_ELEMENT_TYPE = "https://schema.metadatacenter.org/core/TemplateElement"

IGNORE_KEYS = [ "@id", "pav:createdOn", "pav:createdOn", "pav:createdBy", "pav:lastUpdatedOn", "oslc:modifiedBy", "title", "description"]


##TODO add required properties from the schema
##TODO extract the schema:name from the "id" property

cedar_tmpl_element = Template('''
{
"$schema": "http://json-schema.org/draft-04/schema#",
"@id": "",
"@type": "{{ CEDAR_TEMPLATE_ELEMENT_TYPE }}",
"@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "pav": "http://purl.org/pav/",
    "oslc": "http://open-services.net/ns/core#",
    "schema": "http://schema.org/",
    "schema:name": {
      "@type": "xsd:string"
    },
    "schema:description": {
      "@type": "xsd:string"
    },
    "pav:createdOn": {
      "@type": "xsd:dateTime"
    },
    "pav:createdBy": {
      "@type": "@id"
    },
    "pav:lastUpdatedOn": {
      "@type": "xsd:dateTime"
    },
    "oslc:modifiedBy": {
      "@type": "@id"
    }
  },
"type": "object",
"title": "{{ title }}", 
"description": "{{ title }} generated by the mircat2cedar python tool. ",
"schema:name": "{{ id }}",
"schema:description": "{{ description }}",
"schema:schemaVersion": "1.3.0",
"_ui": { 
    "order": [ 
    {% for item in properties %}  "{{ item }}"{% if not loop.last %},{% endif %}
    {% endfor %} ],
    "propertyLabels": {
    {% for item in properties %}   "{{ item }}" : "{{ item }}"{% if not loop.last %},{% endif %}
    {% endfor %} }
 },
  "pav:createdOn": "{{ DATE  }}",
  "pav:lastUpdatedOn": "{{ DATE  }}",
  "pav:createdBy": "{{ MIRCAT2CEDAR }}",
  "oslc:modifiedBy": "{{ MIRCAT2CEDAR }}",
  "required": [
    "@context",
    "@id"
  ],
  "properties": {
  {% for item in properties %}
  
  "{{ item }}": {
      "title": "{{ item }} field schema",
      "properties": {
        "@type": {
          "oneOf": [
            {
              "format": "uri",
              "type": "string"
            },
            {
              "uniqueItems": true,
              "minItems": 1,
              "type": "array",
              "items": {
                "format": "uri",
                "type": "string"
              }
            }
          ]
        },
        "@value": {
          "type": [
            {{ item.type }}
            "null"
          ]
        },
        "rdfs:label": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "schema:description": "{{ item }}",
      "additionalProperties": "false",
      "oslc:modifiedBy": "{{ MIRCAT2CEDAR }}",
      "pav:createdOn": "{{ DATE }}",
      "_ui": {
        "inputType": "textfield"
      },
      "description": "{{ item }} field schema autogenerated by {{ MIRCAT }}",
      "pav:lastUpdatedOn": "{{ DATE }}",
      "required": [
        "@value"
      ],
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "_valueConstraints": {
        "requiredValue": false
      },
      "pav:createdBy": "{{ MIRCAT }}",
      "schema:name": "{{ item }}",
      "@id": "TODO",
      "schema:schemaVersion": "1.3.0",
      "@context": {
        "schema": "http://schema.org/",
        "schema:description": {
          "@type": "xsd:string"
        },
        "pav": "http://purl.org/pav/",
        "pav:createdBy": {
          "@type": "@id"
        },
        "oslc:modifiedBy": {
          "@type": "@id"
        },
        "pav:createdOn": {
          "@type": "xsd:dateTime"
        },
        "oslc": "http://open-services.net/ns/core#",
        "schema:name": {
          "@type": "xsd:string"
        },
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav:lastUpdatedOn": {
          "@type": "xsd:dateTime"
        }
      },
      "type": "object",
      "$schema": "http://json-schema.org/draft-04/schema#"
    }{% if not loop.last %},{% endif %}
  {% endfor %}
  },
 "additionalProperties": {% if additionalProperties %} "{{ additionalProperties }}" {% else %} "true" {% endif%} 
}
''')



def convert_template_element(jsonschema_filename):
    try:
        with open(jsonschema_filename, 'r') as orig_schema_file:
            orig_schema = json.load(orig_schema_file)
            cedar_schema = cedar_tmpl_element.render(orig_schema,
                                                     CEDAR_TEMPLATE_ELEMENT_TYPE= CEDAR_TEMPLATE_ELEMENT_TYPE,
                                                     DATE= datetime.datetime.isoformat(datetime.datetime.now()),
                                                     MIRCAT2CEDAR = "mircat2cedar tool, part of ISA-tools ")
            print(cedar_schema)
            return cedar_schema

    except IOError:
        logging.error("Error opening schema file")


def json_pretty_dump(json_object, output_file):
    return json.dump(json_object,  output_file, sort_keys=True, indent=4, separators=(',', ': '))

"""
Compare two dictionaries d1 and d2, ignoring the list of keys given as ignore_keys
"""
def equal_dicts(d1, d2, ignore_keys):
    ignored = set(ignore_keys)
    for k1, v1 in iter(d1.items()):
        if k1 not in ignored and (k1 not in d2 or d2[k1] != v1):
            return False
    for k2, v2 in iter(d2.items()):
        if k2 not in ignored and k2 not in d1:
            return False
    return True


"""
Return the difference between two dictionaries d1 and d2, ignoring the list of keys given as ignore_keys
"""
def diff_dicts(d1, d2, ignore_keys):
    ignored = set(ignore_keys)
    diff = set()
    for k1, v1 in iter(d1.items()):
        if k1 not in ignored and (k1 not in d2 or d2[k1] != v1):
            diff.add(k1)
    for k2, v2 in iter(d2.items()):
        if k2 not in ignored and k2 not in d1:
            diff.add(k2)
    return diff





