import json
import os
import logging
from jinja2 import Template
import datetime
from cedar.utils import set_template_element_property_minimals, set_sub_context, set_context, set_stripped_properties


cedar_template_element = Template('''
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "@id": "",
    "@context": {{TEMPLATE_CONTEXT | tojson}},
    "@type": "{{TEMPLATE_TYPE}}",
    "type": "object",
    "title": "{{title}} element schema", 
    "description": "{{description}} ",
    "schema:name": "{{id}}",
    "schema:description": "{{description}}",
    "schema:schemaVersion": "1.4.0",
    "bibo:status":"bibo:draft",
    "pav:version":"0.1",
    "pav:createdOn": "{{NOW}}",
    "pav:lastUpdatedOn": "{{NOW}}",
    "pav:createdBy": "{{USER_URL}}",
    "oslc:modifiedBy": "{{USER_URL}}",
    "_ui": { 
        "order": [ 
            {% for item in properties %}
                {% if not item in props %} "{{item}}" {% if not loop.last %},{% endif %} {% endif %}       
            {% endfor %} 
        ],
        "propertyLabels": {
            {% for item in properties %} 
                {% if not item in props %}  
                    "{{item}}" : "{{item}}"{% if not loop.last %},{% endif %} 
                {% endif %}
            {% endfor %}
        }
    },
    {% set requiredList = required %}
    "required":[
        "@context",
        "@id"
        {% for item in requiredList %}
            ,"{{item}}"{% if not loop.last %},{% endif %}
        {% endfor %}
    ],
    "properties": {
        {% for itemKey, itemVal in PROP_CONTEXT.items() %}    
            "{{itemKey}}": {{itemVal | tojson}} {% if not loop.last %},{% endif %}
        {% endfor %},
        {% for itemKey, itemVal in TEMP_PROP.items() %}
            {% if 'items' in itemVal or '$ref' in itemVal %}
                {% if itemKey in SUB_SPECS %}
                     "{{itemKey}}": {{SUB_SPECS[itemKey] | tojson}}
                {% else %}
                    "{{itemKey}}": "test"
                {% endif %}
            {% else %}               
                "{{itemKey}}": {
                    "@context": {{TEMPLATE_CONTEXT | tojson}},
                    "title": "{{itemKey}} field schema generated by {{MIRCAT}}",
                    "bibo:status":"bibo:draft",
                    "pav:version":"0.1",
                    "schema:description": "{{itemKey}}",  
                    "additionalProperties": false,
                    "oslc:modifiedBy": "{{USER_URL}}",
                    "pav:createdOn": "{{NOW}}",
                    "_ui": {
                        "inputType": "textfield"
                    },
                    "description": 
                        {% if itemVal.description %} "{{itemVal.description}}" 
                        {%else %} "{{item}} autogenerated by {{MIRCAT}}" 
                        {% endif %},
                    "pav:lastUpdatedOn": "{{NOW}}",
                    "required": [
                        "@value"
                    ],
                    "@type": "https://schema.metadatacenter.org/core/TemplateField",
                    "_valueConstraints": {
                        "requiredValue":{% if (requiredList is defined) and (itemKey in requiredList) %} true {% else %} false {% endif%}
                    },
                    "pav:createdBy": "{{USER_URL}}",
                    "schema:name": "{{itemKey}}",
                    "@id": "",
                    "schema:schemaVersion": "1.4.0",
                    "type": "object",
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "properties": {
                        "@type": {
                            "oneOf": [
                                {
                                  "format": "uri",
                                  "type": "string"
                                },
                                {
                                    "uniqueItems": true,
                                    "minItems": 1,
                                    "type": "array",
                                    "items": {
                                        "format": "uri",
                                        "type": "string"
                                    }
                                }
                            ]
                        },
                        "@value": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "rdfs:label": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    }
                }
            {% endif %}                                                               
            {% if not loop.last %},{% endif %}
        {% endfor %}
    },
     "additionalProperties": {% if additionalProperties %} {{additionalProperties}} {% else %} false {% endif%}
}
''')


def convert_template_element(schema_file_path):
    cedar_type = "https://schema.metadatacenter.org/core/TemplateElement"
    try:
        with open(schema_file_path, 'r') as orig_schema_file:

            now = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S-0700')
            schema_as_json = json.load(orig_schema_file)
            orig_schema_file.close()
            property_context = set_template_element_property_minimals(set_sub_context(schema_as_json))

            sub_spec_container = {}
            sub_spec = set_sub_specs(schema_as_json['properties'], sub_spec_container)

            cedar_schema = cedar_template_element.render(schema_as_json,
                                                         TEMPLATE_TYPE=cedar_type,
                                                         TEMPLATE_CONTEXT=set_context(),
                                                         NOW=now,
                                                         USER_URL="https://metadatacenter.org/users/e856d779-6e24-4d72-a4e6-f7ae4b6419e2",
                                                         MIRCAT="mircat-tools",
                                                         PROP_CONTEXT=property_context,
                                                         TEMP_PROP=set_stripped_properties(schema_as_json),
                                                         SUB_SPECS=sub_spec)

            return cedar_schema

    except IOError:
        logging.error("Error opening schema file")


def json_pretty_dump(json_object, output_file):
    return json.dump(json_object,  output_file, sort_keys=False, indent=4, separators=(',', ': '))


def set_sub_specs(schema, sub_spec_container):
    ignored_key = ["@id", "@type", "@context"]
    data_dir = os.path.join(os.path.dirname(__file__), "../tests/data")

    for itemKey, itemVal in schema.items():
        if itemKey not in ignored_key:
            if '$ref' in itemVal:
                schema = os.path.join(data_dir, itemVal['$ref'].replace('#', ''))
                sub_spec = json.loads(convert_template_element(schema))
                sub_spec_container[itemKey] = sub_spec
                sub_spec_container = set_sub_specs(sub_spec['properties'], sub_spec_container)

            elif 'items' in itemVal:
                schema = os.path.join(data_dir, itemVal['items']['$ref'].replace('#', ''))
                sub_spec = json.loads(convert_template_element(schema))
                sub_spec_container[itemKey] = sub_spec
                sub_spec_container = set_sub_specs(sub_spec['properties'], sub_spec_container)

    return sub_spec_container